/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IceCream;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DEVANSHI SRIVASTAVA
 */
public class IC extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form IC
     */
    public IC() {
        initComponents();
        
        but.addMouseListener(this);
        van.addMouseListener(this);
        cho.addMouseListener(this);
        man.addMouseListener(this);
        tut.addMouseListener(this);
        cs.addMouseListener(this);
        vs.addMouseListener(this);
    }
    
    DefaultTableModel model=new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tut = new javax.swing.JLabel();
        but = new javax.swing.JLabel();
        cho = new javax.swing.JLabel();
        man = new javax.swing.JLabel();
        van = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        vs = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(205, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setBackground(new java.awt.Color(204, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 5, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEVZI ICE CREAM SHOP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(940, 150));

        tut.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\New folder\\tutty-fruity-ice-cream-500x500.jpg")); // NOI18N
        tut.setText("jLabel5");

        but.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\New folder\\butterscotch-ice-cream-500x500.jpg")); // NOI18N
        but.setText("jLabel5");

        cho.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\New folder\\chocolate-ice-cream-500x500.jpg")); // NOI18N
        cho.setText("jLabel5");

        man.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\New folder\\mango-ice-cream-500x500.jpg")); // NOI18N
        man.setText("jLabel5");

        van.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\New folder\\vanilla-ice-cream-500x500.jpg")); // NOI18N
        van.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cho, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(man, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(van, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tut, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cho, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(man, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(van, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ice-Cream", jPanel2);

        vs.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\New folder\\vanilla-softy-premix-500x500.jpg")); // NOI18N
        vs.setText("jLabel2");

        cs.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\New folder\\blackcurrant-softy-premix-500x500.jpeg")); // NOI18N
        cs.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(cs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cs)
                    .addComponent(vs))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Softy", jPanel4);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("TOTAL");

        tf.setBackground(new java.awt.Color(0, 0, 0));
        tf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf.setForeground(new java.awt.Color(255, 255, 255));
        tf.setText("0");
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(76, 76, 76)
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel but;
    private javax.swing.JLabel cho;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel man;
    private javax.swing.JTable tab;
    private javax.swing.JTextField tf;
    private javax.swing.JLabel tut;
    private javax.swing.JLabel van;
    private javax.swing.JLabel vs;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
    if(e.getSource() == cho) 
    {
        String name="Chocolate";
        int price=150;
        
        int qty;
        qty = Integer.parseInt(JOptionPane.showInputDialog("Enter quantity"));
        int tot=price*qty;
        
        model = (DefaultTableModel)tab.getModel();
        
        model.addRow(new Object[]
        {
            name,
            price,
            qty,
            tot,
        });
        
        int sum=0;
        for(int i=0;i<tab.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(tab.getValueAt(i,3).toString());
        }
        tf.setText(Integer.toString(sum));
    }
    
    else if(e.getSource() == van) 
    {
        String name="Vanilla";
        int price=100;
        
        int qty;
        qty = Integer.parseInt(JOptionPane.showInputDialog("Enter quantity"));
        int tot=price*qty;
        
        model = (DefaultTableModel)tab.getModel();
        
        model.addRow(new Object[]
        {
            name,
            price,
            qty,
            tot,
        });
        
        int sum=0;
        for(int i=0;i<tab.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(tab.getValueAt(i,3).toString());
        }
        tf.setText(Integer.toString(sum));
    }
    
    else if(e.getSource() == man) 
    {
        String name="Mango";
        int price=200;
        
        int qty;
        qty = Integer.parseInt(JOptionPane.showInputDialog("Enter quantity"));
        int tot=price*qty;
        
        model = (DefaultTableModel)tab.getModel();
        
        model.addRow(new Object[]
        {
            name,
            price,
            qty,
            tot,
        });
        
        int sum=0;
        for(int i=0;i<tab.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(tab.getValueAt(i,3).toString());
        }
        tf.setText(Integer.toString(sum));
    }
    
    else if(e.getSource() == but) 
    {
        String name="ButterScotch";
        int price=150;
        
        int qty;
        qty = Integer.parseInt(JOptionPane.showInputDialog("Enter quantity"));
        int tot=price*qty;
        
        model = (DefaultTableModel)tab.getModel();
        
        model.addRow(new Object[]
        {
            name,
            price,
            qty,
            tot,
        });
        
        int sum=0;
        for(int i=0;i<tab.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(tab.getValueAt(i,3).toString());
        }
        tf.setText(Integer.toString(sum));
    }
    
    else if(e.getSource() == tut) 
    {
        String name="Tutti-Frutti";
        int price=250;
        
        int qty;
        qty = Integer.parseInt(JOptionPane.showInputDialog("Enter quantity"));
        int tot=price*qty;
        
        model = (DefaultTableModel)tab.getModel();
        
        model.addRow(new Object[]
        {
            name,
            price,
            qty,
            tot,
        });
        
        int sum=0;
        for(int i=0;i<tab.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(tab.getValueAt(i,3).toString());
        }
        tf.setText(Integer.toString(sum));
    }
    
    else if(e.getSource() == cs) 
    {
        String name="Chocolate Softy";
        int price=300;
        
        int qty;
        qty = Integer.parseInt(JOptionPane.showInputDialog("Enter quantity"));
        int tot=price*qty;
        
        model = (DefaultTableModel)tab.getModel();
        
        model.addRow(new Object[]
        {
            name,
            price,
            qty,
            tot,
        });
        
        int sum=0;
        for(int i=0;i<tab.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(tab.getValueAt(i,3).toString());
        }
        tf.setText(Integer.toString(sum));
    }
    
    else if(e.getSource() == vs) 
    {
        String name="Vanilla Softy";
        int price=250;
        
        int qty;
        qty = Integer.parseInt(JOptionPane.showInputDialog("Enter quantity"));
        int tot=price*qty;
        
        model = (DefaultTableModel)tab.getModel();
        
        model.addRow(new Object[]
        {
            name,
            price,
            qty,
            tot,
        });
        
        int sum=0;
        for(int i=0;i<tab.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(tab.getValueAt(i,3).toString());
        }
        tf.setText(Integer.toString(sum));
    }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
